#  Copyright (C) 2025–2026 Comicarr contributors
#
#  This file is part of Comicarr.
#
#  Comicarr is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

"""Machine-readable evidence for every packaged third-party vendor root.

``evidence-recorded`` means the copied tree contains identifiable license
evidence; it is not a legal clearance decision. ``unresolved`` means the
repository cannot establish redistribution authority for the bundled snapshot.
"""

ALLOWED_REDISTRIBUTION_STATUSES = frozenset({"evidence-recorded", "unresolved"})
COMICARR_IMPORT_REVISION = "45720b948f8c0cc9153412171dca8891e266f1c8"

# Temporary compatibility debt. The wheel contains ``comicarr._vendor.certgen``
# but this caller still uses the historical top-level name. U5 owns draining the
# import while its structural ratchet is introduced.
LEGACY_TOP_LEVEL_VENDOR_IMPORTS = {
    "certgen": ("comicarr/app/core/security.py",),
}

VENDOR_PROVENANCE = {
    "bencode": {
        "integration_owner": "Comicarr",
        "path": "comicarr/_vendor/bencode.py",
        "custody_source_url": "https://github.com/mylar3/mylar3",
        "custody_source_path": "lib/bencode.py",
        "custody_revision": None,
        "upstream_source_url": None,
        "upstream_revision": None,
        "import_revision": COMICARR_IMPORT_REVISION,
        "upstream_version": "20111107",
        "version_evidence": ("comicarr/_vendor/bencode.py",),
        "license_expression": "MIT",
        "license_evidence": ("comicarr/_vendor/bencode.py",),
        "license_conflict_evidence": (),
        "notice_files": (),
        "origin_candidates": (),
        "replacement_candidates": (),
        "partial_attributions": (),
        "redistribution_status": "evidence-recorded",
        "unresolved_reasons": (),
        "local_modifications": "Inherited Python 3 compatibility changes",
        "packaged_snapshot_sha256": "f2087ce3ed6834fe58a5c9bca2fafc817c837a4388af53dede1eb21288ad26ce",
    },
    "certgen": {
        "integration_owner": "Comicarr",
        "path": "comicarr/_vendor/certgen.py",
        "custody_source_url": "https://github.com/mylar3/mylar3",
        "custody_source_path": "lib/certgen.py",
        "custody_revision": None,
        "upstream_source_url": None,
        "upstream_revision": None,
        "import_revision": COMICARR_IMPORT_REVISION,
        "upstream_version": None,
        "version_evidence": (),
        "license_expression": "LGPL-2.1-or-later",
        "license_evidence": ("comicarr/_vendor/certgen.py",),
        "license_conflict_evidence": (),
        "notice_files": (),
        "origin_candidates": (),
        "replacement_candidates": (),
        "partial_attributions": (),
        "redistribution_status": "evidence-recorded",
        "unresolved_reasons": (),
        "local_modifications": "No upstream revision recovered; referenced LGPL2.1.txt is absent",
        "packaged_snapshot_sha256": "b18d3b0f531a7340fb1186ef714eb934410fb0425a914f72cd2d1fb77ed5c1b0",
    },
    "comictaggerlib": {
        "integration_owner": "Comicarr",
        "path": "comicarr/_vendor/comictaggerlib",
        "custody_source_url": "https://github.com/mylar3/mylar3",
        "custody_source_path": "lib/comictaggerlib",
        "custody_revision": None,
        "upstream_source_url": None,
        "upstream_revision": None,
        "import_revision": COMICARR_IMPORT_REVISION,
        "upstream_version": "1.3.5",
        "version_evidence": ("comicarr/_vendor/comictaggerlib/ctversion.py",),
        "license_expression": "Apache-2.0",
        "license_evidence": (
            "comicarr/_vendor/comictaggerlib/main.py",
            "comicarr/_vendor/comictaggerlib/comicapi/comicarchive.py",
        ),
        "license_conflict_evidence": (),
        "notice_files": (),
        "origin_candidates": (),
        "replacement_candidates": ("https://github.com/comictagger/comictagger",),
        "partial_attributions": (),
        "redistribution_status": "evidence-recorded",
        "unresolved_reasons": (),
        "local_modifications": "Bundled historical fork; retain per-file notices",
        "packaged_snapshot_sha256": "30ecae7ee68e334fc2af567f033569071b2dc09faaaca065353765cc00bb42c0",
    },
    "deluge_client": {
        "integration_owner": "Comicarr",
        "path": "comicarr/_vendor/deluge_client",
        "custody_source_url": "https://github.com/mylar3/mylar3",
        "custody_source_path": "lib/deluge_client",
        "custody_revision": None,
        "upstream_source_url": None,
        "upstream_revision": None,
        "import_revision": COMICARR_IMPORT_REVISION,
        "upstream_version": None,
        "version_evidence": (),
        "license_expression": "MIT",
        "license_evidence": ("comicarr/_vendor/deluge_client/LICENSE",),
        "license_conflict_evidence": (),
        "notice_files": ("comicarr/_vendor/deluge_client/LICENSE",),
        "origin_candidates": (),
        "replacement_candidates": (),
        "partial_attributions": (),
        "redistribution_status": "evidence-recorded",
        "unresolved_reasons": (),
        "local_modifications": "Bundled RPC implementation",
        "packaged_snapshot_sha256": "c05c2a30965820a6c4fb1347c64eeb66d42085cc036d0f8a0816a1dea9c49f3d",
    },
    "get_image_size": {
        "integration_owner": "Comicarr",
        "path": "comicarr/_vendor/get_image_size.py",
        "custody_source_url": "https://github.com/mylar3/mylar3",
        "custody_source_path": "lib/get_image_size.py",
        "custody_revision": None,
        "upstream_source_url": None,
        "upstream_revision": None,
        "import_revision": COMICARR_IMPORT_REVISION,
        "upstream_version": None,
        "version_evidence": ("comicarr/_vendor/get_image_size.py",),
        "license_expression": "MIT",
        "license_evidence": ("comicarr/_vendor/get_image_size.py",),
        "license_conflict_evidence": (),
        "notice_files": (),
        "origin_candidates": (),
        "replacement_candidates": (),
        "partial_attributions": (),
        "redistribution_status": "evidence-recorded",
        "unresolved_reasons": (),
        "local_modifications": "Packaged support module with no current first-party import",
        "packaged_snapshot_sha256": "3d34c63b8dbcd66fb1ec336fea5dfe0b3ae3a3d98fcd68b6993e9bac087db0c6",
    },
    "mega": {
        "integration_owner": "Comicarr",
        "path": "comicarr/_vendor/mega",
        "custody_source_url": "https://github.com/mylar3/mylar3",
        "custody_source_path": "lib/mega",
        "custody_revision": "9ad1b5d7d1be7c90cd49e6ec4149ade3d05e3292",
        "upstream_source_url": "https://github.com/odwyersoftware/mega.py",
        "upstream_revision": "34f3e7335992589eed8f08e675c5fb3038139355",
        "import_revision": COMICARR_IMPORT_REVISION,
        "upstream_version": "1.0.8",
        "version_evidence": (
            "https://github.com/odwyersoftware/mega.py/blob/34f3e7335992589eed8f08e675c5fb3038139355/setup.py",
        ),
        "license_expression": "NOASSERTION",
        "license_evidence": (),
        "license_conflict_evidence": (
            "https://github.com/odwyersoftware/mega.py/blob/34f3e7335992589eed8f08e675c5fb3038139355/LICENSE",
            "https://github.com/odwyersoftware/mega.py/blob/34f3e7335992589eed8f08e675c5fb3038139355/setup.py",
        ),
        "notice_files": ("comicarr/_vendor/mega/NOTICE",),
        "origin_candidates": (),
        "replacement_candidates": (),
        "partial_attributions": (),
        "redistribution_status": "unresolved",
        "unresolved_reasons": (
            "the identified 1.0.8 base has conflicting Apache-2.0 and Creative Commons license metadata",
            "copied files contain no authoritative license notice that resolves that conflict",
        ),
        "local_modifications": "Mylar3 changed 34 lines in mega.py; Comicarr later namespaced the inherited tree",
        "packaged_snapshot_sha256": "5b027968c3a035eca8237eebf91739ed61e2b2a536595f4d5702e0aff023db25",
    },
    "qbittorrent": {
        "integration_owner": "Comicarr",
        "path": "comicarr/_vendor/qbittorrent",
        "custody_source_url": "https://github.com/mylar3/mylar3",
        "custody_source_path": "lib/qbittorrent",
        "custody_revision": None,
        "upstream_source_url": None,
        "upstream_revision": None,
        "import_revision": COMICARR_IMPORT_REVISION,
        "upstream_version": None,
        "version_evidence": (),
        "license_expression": "MIT",
        "license_evidence": ("comicarr/_vendor/qbittorrent/LICENSE",),
        "license_conflict_evidence": (),
        "notice_files": ("comicarr/_vendor/qbittorrent/LICENSE",),
        "origin_candidates": (),
        "replacement_candidates": ("https://github.com/rmartin16/qbittorrent-api",),
        "partial_attributions": (),
        "redistribution_status": "evidence-recorded",
        "unresolved_reasons": (),
        "local_modifications": (
            "Bundled Web API client; exact upstream revision unidentified. "
            "Comicarr adds a DEFAULT_TIMEOUT to every WebUI request so a hung "
            "client cannot block the single-threaded torrent monitor."
        ),
        "packaged_snapshot_sha256": "b0251f4e6dd857e0f0a1107e30e851f8c524b15dd7b294bedbd2390d964f2b4f",
    },
    "rtorrent": {
        "integration_owner": "Comicarr",
        "path": "comicarr/_vendor/rtorrent",
        "custody_source_url": "https://github.com/mylar3/mylar3",
        "custody_source_path": "lib/rtorrent",
        "custody_revision": None,
        "upstream_source_url": None,
        "upstream_revision": None,
        "import_revision": COMICARR_IMPORT_REVISION,
        "upstream_version": "0.2.9",
        "version_evidence": ("comicarr/_vendor/rtorrent/__init__.py",),
        "license_expression": "MIT AND (GPL-2.0-or-later WITH OpenSSL-exception) AND LicenseRef-Secret-Labs",
        "license_evidence": (
            "comicarr/_vendor/rtorrent/__init__.py",
            "comicarr/_vendor/rtorrent/lib/xmlrpc/clients/scgi.py",
            "comicarr/_vendor/rtorrent/lib/xmlrpc/transports/scgi.py",
        ),
        "license_conflict_evidence": (),
        "notice_files": (),
        "origin_candidates": (),
        "replacement_candidates": (),
        "partial_attributions": (),
        "redistribution_status": "evidence-recorded",
        "unresolved_reasons": (),
        "local_modifications": "Bundled mixed-license XML-RPC/SCGI client",
        "packaged_snapshot_sha256": "8eebf1a33e0f83852c5e79d23e16073a73a008cf90b5cf06f0b7c97fdd3dda5a",
    },
    "transmissionrpc": {
        "integration_owner": "Comicarr",
        "path": "comicarr/_vendor/transmissionrpc",
        "custody_source_url": "https://github.com/mylar3/mylar3",
        "custody_source_path": "lib/transmissionrpc",
        "custody_revision": None,
        "upstream_source_url": None,
        "upstream_revision": None,
        "import_revision": COMICARR_IMPORT_REVISION,
        "upstream_version": "0.11",
        "version_evidence": ("comicarr/_vendor/transmissionrpc/__init__.py",),
        "license_expression": "MIT",
        "license_evidence": ("comicarr/_vendor/transmissionrpc/__init__.py",),
        "license_conflict_evidence": (),
        "notice_files": (),
        "origin_candidates": (),
        "replacement_candidates": ("https://github.com/Trim21/transmission-rpc",),
        "partial_attributions": (),
        "redistribution_status": "evidence-recorded",
        "unresolved_reasons": (),
        "local_modifications": "Bundled historical RPC client",
        "packaged_snapshot_sha256": "c3e2128ae6e541b117baed3478c7ff3e7d5c7131739d7515d1c3c3acbb970124",
    },
    "utorrent": {
        "integration_owner": "Comicarr",
        "path": "comicarr/_vendor/utorrent",
        "custody_source_url": "https://github.com/mylar3/mylar3",
        "custody_source_path": "lib/utorrent",
        "custody_revision": None,
        "upstream_source_url": None,
        "upstream_revision": None,
        "import_revision": COMICARR_IMPORT_REVISION,
        "upstream_version": None,
        "version_evidence": (),
        "license_expression": "NOASSERTION",
        "license_evidence": (),
        "license_conflict_evidence": (),
        "notice_files": ("comicarr/_vendor/utorrent/NOTICE",),
        "origin_candidates": (
            {
                "url": "https://github.com/ftao/py-utorrent",
                "revision": "35c4298463247165012ef8f8b4647f10a2fd5bd4",
                "paths": ("utorrent/client.py", "utorrent/upload.py"),
                "relationship": "probable-direct-base",
                "confidence": "high",
                "evidence": (
                    "upload.py is byte-identical at the Comicarr import revision",
                    "client.py has 0.8483 line similarity with localized Mylar3 changes",
                ),
            },
        ),
        "replacement_candidates": (),
        "partial_attributions": (
            {
                "url": "http://www.doughellmann.com/PyMOTW/urllib2/",
                "applies_to": ("comicarr/_vendor/utorrent/upload.py:1",),
                "relationship": "helper-attribution-only",
            },
        ),
        "redistribution_status": "unresolved",
        "unresolved_reasons": (
            "the probable py-utorrent base has no license file or license metadata",
            "the original copyright and redistribution authority remain unidentified",
            "the PyMOTW attribution covers only a helper and supplies no bundled license",
            "uTorrent 3.0+ is a compatibility target, not a client library version",
        ),
        "local_modifications": (
            "Ported to Python 3 and namespaced by Comicarr. Comicarr adds a "
            "DEFAULT_TIMEOUT to every WebUI request so a hung client cannot "
            "block the single-threaded torrent monitor."
        ),
        "packaged_snapshot_sha256": "c0cd1eeb3cae1068b081c2afeb113b16fb14de42b98bd7ad83d9ad9438e942f9",
    },
}
