#  This file is part of Comicarr.
#
#  Comicarr is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

"""Emit the settings wire types from the config registry.

    python3 scripts/generate_config_types.py           # rewrite the committed module
    python3 scripts/generate_config_types.py --check    # fail if it is stale

Output is committed and must be regenerated whenever a key's name, type, or
`readable`/`writable` flag changes in `comicarr/app/config/registry.py`, or
whenever `get_safe_config`'s synthesised fields change in `service.py`. The
`--check` mode is wired into `npm run lint` and the Backend Lint CI job;
`npm run lint:fix` rewrites the module.

`--check` compares in memory and prints a unified diff — it never touches the
working tree, so a failing lint leaves nothing to clean up.

This script deliberately imports the registry *by path* rather than through the
`comicarr` package, so it runs on a bare interpreter with no project
dependencies installed. See `_load_registry`.

The output is Prettier-clean by construction, so no formatting pass is needed
between generating and committing.

Two types, because the readable and writable sets are not nested — 15 keys are
write-only secrets and 10 are read-only:

  ReadableConfig — what `get_safe_config` returns. Every field is optional:
      `get_safe_config` skips a key whose value is None (`service.py:250`), so
      an unset path is *absent*, not null.
  WritableConfig — what `update_config` accepts.

Keys are lowercase on the wire: `get_safe_config` lowercases on the way out
(`service.py:254`) and `update_config` uppercases on the way in
(`service.py:294`).
"""

from __future__ import annotations

import argparse
import difflib
import importlib.util
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

TS = {str: "string", int: "number", bool: "boolean"}

REGISTRY_PY = ROOT / "comicarr" / "app" / "config" / "registry.py"
SERVICE_PY = ROOT / "comicarr" / "app" / "system" / "service.py"
OUTPUT = ROOT / "frontend" / "src" / "types" / "config.generated.ts"


def _load_registry() -> dict:
    """Load `registry.py` by path, bypassing `comicarr/__init__.py`.

    Importing `comicarr.app.config.registry` normally would execute the package
    `__init__`, which pulls in requests, apscheduler, sqlalchemy and the legacy
    modules — making this script need a full `uv sync`. `registry.py` is a
    stdlib-only leaf, so loading it directly keeps the generator runnable from a
    bare interpreter. That is what lets the freshness check live in the Backend
    Lint job, which installs ruff and nothing else.
    """
    spec = importlib.util.spec_from_file_location("comicarr_config_registry", REGISTRY_PY)
    module = importlib.util.module_from_spec(spec)
    # dataclasses resolves the owning module out of sys.modules while it
    # processes @dataclass, so register before executing.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module.REGISTRY


def _extra_readable_fields() -> list[tuple[str, str]]:
    """Fields `get_safe_config` synthesises that no registry key backs."""
    source = SERVICE_PY.read_text()

    indicators = re.search(r"secret_indicators = \{(.*?)\n    \}", source, re.S)
    fields = [(name, "boolean") for name in re.findall(r'"([a-z0-9_]+_set)":', indicators.group(1))]

    # Derived download-client labels, appended after the allowlist loop.
    for name in re.findall(r'result\["([a-z_]+_label)"\]', source):
        fields.append((name, "string"))
    return sorted(set(fields))


def render() -> str:
    registry = _load_registry()
    readable = [k for k in registry.values() if k.readable]
    writable = [k for k in registry.values() if k.writable]

    out = [
        "// GENERATED by scripts/generate_config_types.py — do not edit by hand.",
        "// Source of truth: comicarr/app/config/registry.py",
        "",
        "/** Shape of `GET /api/config`. Every field is optional: get_safe_config",
        " *  omits a key whose value is None rather than sending null. */",
        "export interface ReadableConfig {",
    ]
    for key in readable:
        out.append("  %s?: %s;" % (key.wire_name, TS[key.type]))
    if extras := _extra_readable_fields():
        out.append("")
        out.append("  // Synthesised by get_safe_config; not registry-backed.")
        for name, ts_type in extras:
            out.append("  %s?: %s;" % (name, ts_type))
    out.append("}")
    out.append("")
    out.append("/** Keys `update_config` accepts. */")
    out.append("export interface WritableConfig {")
    for key in writable:
        out.append("  %s?: %s;" % (key.wire_name, TS[key.type]))
    out.append("}")
    out.append("")
    out.append("/** SettingsPage seeds formData from the readable config, then merges")
    out.append(" *  writable edits into it — so it is both shapes at once. */")
    out.append("export type SettingsFormData = ReadableConfig & WritableConfig;")

    print(
        "# %d readable, %d writable, %d synthesised" % (len(readable), len(writable), len(_extra_readable_fields())),
        file=sys.stderr,
    )
    # The single trailing newline is the one Prettier wants; a blank final line
    # would fail `npm run format:check`.
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the committed module is stale, without rewriting it",
    )
    args = parser.parse_args(argv)

    generated = render()
    relative = OUTPUT.relative_to(ROOT)

    if not args.check:
        OUTPUT.write_text(generated)
        return 0

    committed = OUTPUT.read_text() if OUTPUT.exists() else ""
    if committed == generated:
        return 0

    diff = difflib.unified_diff(
        committed.splitlines(keepends=True),
        generated.splitlines(keepends=True),
        fromfile="%s (committed)" % relative,
        tofile="%s (regenerated)" % relative,
    )
    sys.stdout.writelines(diff)
    print(
        "\n%s is stale. Run `npm run lint:fix:generated` (or "
        "`python3 scripts/generate_config_types.py`) and commit the result." % relative,
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
