#  This file is part of Comicarr.
#
#  Comicarr is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

"""Emit the settings wire types from the config registry.

    python3 scripts/generate_config_types.py > frontend/src/types/config.generated.ts

Output is committed and must be regenerated whenever a key's name, type, or
`readable`/`writable` flag changes in `comicarr/app/config/registry.py`. Nothing
runs this automatically yet — #363 decides which CI lane regenerates and fails
on drift. Until then, `regenerate && git diff --exit-code` is the check.

The output is Prettier-clean by construction, so no formatting pass is needed
between generating and committing.

Two types, because the readable and writable sets are not nested — 15 keys are
write-only secrets and 10 are read-only:

  ReadableConfig — what `get_safe_config` returns. Every field is optional:
      `get_safe_config` skips a key whose value is None (`service.py:250`), so
      an unset path is *absent*, not null.
  WritableConfig — what `update_config` accepts.

Keys are lowercase on the wire: `get_safe_config` lowercases on the way out
(`service.py:254`) and `update_config` uppercases on the way in
(`service.py:294`).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from comicarr.app.config.registry import REGISTRY  # noqa: E402

TS = {str: "string", int: "number", bool: "boolean"}

SERVICE_PY = ROOT / "comicarr" / "app" / "system" / "service.py"


def _extra_readable_fields() -> list[tuple[str, str]]:
    """Fields `get_safe_config` synthesises that no registry key backs."""
    source = SERVICE_PY.read_text()

    indicators = re.search(r"secret_indicators = \{(.*?)\n    \}", source, re.S)
    fields = [(name, "boolean") for name in re.findall(r'"([a-z0-9_]+_set)":', indicators.group(1))]

    # Derived download-client labels, appended after the allowlist loop.
    for name in re.findall(r'result\["([a-z_]+_label)"\]', source):
        fields.append((name, "string"))
    return sorted(set(fields))


def main() -> int:
    readable = [k for k in REGISTRY.values() if k.readable]
    writable = [k for k in REGISTRY.values() if k.writable]

    out = [
        "// GENERATED by scripts/generate_config_types.py — do not edit by hand.",
        "// Source of truth: comicarr/app/config/registry.py",
        "",
        "/** Shape of `GET /api/config`. Every field is optional: get_safe_config",
        " *  omits a key whose value is None rather than sending null. */",
        "export interface ReadableConfig {",
    ]
    for key in readable:
        out.append("  %s?: %s;" % (key.wire_name, TS[key.type]))
    if extras := _extra_readable_fields():
        out.append("")
        out.append("  // Synthesised by get_safe_config; not registry-backed.")
        for name, ts_type in extras:
            out.append("  %s?: %s;" % (name, ts_type))
    out.append("}")
    out.append("")
    out.append("/** Keys `update_config` accepts. */")
    out.append("export interface WritableConfig {")
    for key in writable:
        out.append("  %s?: %s;" % (key.wire_name, TS[key.type]))
    out.append("}")
    out.append("")
    out.append("/** SettingsPage seeds formData from the readable config, then merges")
    out.append(" *  writable edits into it — so it is both shapes at once. */")
    out.append("export type SettingsFormData = ReadableConfig & WritableConfig;")

    # print() adds the single trailing newline Prettier wants; an extra "" here
    # would emit a blank final line and fail `npm run format:check`.
    print("\n".join(out))
    print(
        "# %d readable, %d writable, %d synthesised" % (len(readable), len(writable), len(_extra_readable_fields())),
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
