#!/bin/sh
##
##    Based on the init script pattern from headphones.
##
#
#                                   DO NOT EDIT THIS FILE
#
##
## Edit user configuation in /etc/default/comicarr to change
##
## Make sure init script is executable
## sudo chmod +x /opt/comicarr/init.ubuntu
##
## Install the init script
## sudo ln -s /opt/comicarr/init.ubuntu /etc/init.d/comicarr
##
## Create the comicarr daemon user:
## sudo adduser --system --no-create-home comicarr
##
## Make sure /opt/comicarr is owned by the comicarr user
## sudo chown comicarr:nogroup -R /opt/comicarr
##
## Touch the default file to stop the warning message when starting
## sudo touch /etc/default/comicarr
##
## To start comicarr automatically
## sudo  update-rc.d comicarr defaults
##
## To start/stop/restart comicarr
## sudo service comicarr start
## sudo service comicarr stop
## sudo service comicarr restart
##
## COMICARR_USER=         #$RUN_AS, username to run comicarr under, the default is comicarr
## COMICARR_HOME=         #$APP_PATH, the location of Comicarr.py, the default is /opt/comicarr
## COMICARR_DATA=         #$DATA_DIR, the location of comicarr.db, cache, logs, the default is /opt/comicarr
## COMICARR_PIDFILE=      #$PID_FILE, the location of comicarr.pid, the default is /var/run/comicarr/comicarr.pid
## PYTHON_BIN=         #$DAEMON, the location of the python binary, the default is /usr/bin/python
## COMICARR_OPTS=         #$EXTRA_DAEMON_OPTS, extra cli option for comicarr, i.e. " --config=/home/comicarr/config.ini"
## SSD_OPTS=           #$EXTRA_SSD_OPTS, extra start-stop-daemon option like " --group=users"
## COMICARR_PORT=         #$PORT_OPTS, hardcoded port for the webserver, overrides value in config.ini
##
## EXAMPLE if want to run as different user
## add COMICARR_USER=username to /etc/default/comicarr
## otherwise default comicarr is used
#
### BEGIN INIT INFO
# Provides:          comicarr
# Required-Start:    $local_fs $network $remote_fs
# Required-Stop:     $local_fs $network $remote_fs
# Should-Start:      $NetworkManager
# Should-Stop:       $NetworkManager
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts instance of comicarr
# Description:       starts instance of comicarr using start-stop-daemon
### END INIT INFO

# Script name
NAME=comicarr

# App name
DESC=comicarr

SETTINGS_LOADED=FALSE

. /lib/lsb/init-functions

# Source comicarr configuration
if [ -f /etc/default/comicarr ]; then
    SETTINGS=/etc/default/comicarr
else
    log_warning_msg "/etc/default/comicarr not found using default settings.";
fi

check_retval() {
    if [ $? -eq 0 ]; then
        log_end_msg 0
        return 0
    else
        log_end_msg 1
        exit 1
    fi
}

load_settings() {
    if [ $SETTINGS_LOADED != "TRUE" ]; then
        . $SETTINGS

        ## The defaults
        # Run as username
        RUN_AS=${COMICARR_USER-comicarr}

        # Path to app COMICARR_HOME=path_to_app_Comicarr.py
        APP_PATH=${COMICARR_HOME-/opt/comicarr}

        # Data directory where comicarr.db, cache and logs are stored
        DATA_DIR=${COMICARR_DATA-/opt/comicarr}

        # Path to store PID file
        PID_FILE=${COMICARR_PIDFILE-/var/run/comicarr/comicarr.pid}

        # Path to python bin
        DAEMON=${PYTHON_BIN-/usr/bin/python}

        # Extra daemon option like: COMICARR_OPTS=" --config=/home/comicarr/config.ini"
        EXTRA_DAEMON_OPTS=${COMICARR_OPTS-}

        # Extra start-stop-daemon option like START_OPTS=" --group=users"
        EXTRA_SSD_OPTS=${SSD_OPTS-}

        # Hardcoded port to run on, overrides config.ini settings
        [ -n "$COMICARR_PORT" ] && {
            PORT_OPTS=" --port=${COMICARR_PORT} "
        }

        DAEMON_OPTS=" Comicarr.py --quiet --daemon --nolaunch --pidfile=${PID_FILE} --datadir=${DATA_DIR} ${PORT_OPTS}${EXTRA_DAEMON_OPTS}"

        SETTINGS_LOADED=TRUE
    fi

    [ -x $DAEMON ] || {
        log_warning_msg "$DESC: Can't execute daemon, aborting. See $DAEMON";
        return 1;}

    return 0
}

load_settings || exit 0

is_running () {
    # returns 1 when running, else 0.
    if [ -e $PID_FILE ]; then
      PID=`cat $PID_FILE`

      RET=$?
      [ $RET -gt 1 ] && exit 1 || return $RET
    else
      return 1
    fi
}

handle_pid () {
    PID_PATH=`dirname $PID_FILE`
    [ -d $PID_PATH ] || mkdir -p $PID_PATH && chown -R $RUN_AS $PID_PATH > /dev/null || {
        log_warning_msg "$DESC: Could not create $PID_FILE, See $SETTINGS, aborting.";
        return 1;}

    if [ -e $PID_FILE ]; then
        PID=`cat $PID_FILE`
        if ! kill -0 $PID > /dev/null 2>&1; then
            log_warning_msg "Removing stale $PID_FILE"
            rm $PID_FILE
        fi
    fi
}

handle_datadir () {
    [ -d $DATA_DIR ] || mkdir -p $DATA_DIR && chown -R $RUN_AS $DATA_DIR > /dev/null || {
        log_warning_msg "$DESC: Could not create $DATA_DIR, See $SETTINGS, aborting.";
        return 1;}
}

handle_updates () {
    chown -R $RUN_AS $APP_PATH > /dev/null || {
        log_warning_msg "$DESC: $APP_PATH not writable by $RUN_AS for web-updates";
        return 0; }
}

start_comicarr () {
    handle_pid
    handle_datadir
    handle_updates
    if ! is_running; then
        log_daemon_msg "Starting $DESC"
        start-stop-daemon -o -d $APP_PATH -c $RUN_AS --start $EXTRA_SSD_OPTS --pidfile $PID_FILE --exec $DAEMON -- $DAEMON_OPTS
        check_retval
    else
        log_success_msg "$DESC: already running (pid $PID)"
    fi
}

stop_comicarr () {
    if is_running; then
        log_daemon_msg "Stopping $DESC"
        start-stop-daemon -o --stop --pidfile $PID_FILE --retry 15
        check_retval
    else
        log_success_msg "$DESC: not running"
    fi
}

case "$1" in
    start)
        start_comicarr
        ;;
    stop)
        stop_comicarr
        ;;
    restart|force-reload)
        stop_comicarr
        start_comicarr
        ;;
    status)
        status_of_proc -p "$PID_FILE" "$DAEMON" "$DESC"
        ;;
    *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
        exit 1
        ;;
esac

exit 0
